name: CI with Docker

on:
  pull_request:
    branches:
      - main
      - dev
      - test

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      # 1. Servicio de base de datos: Levanta una base de datos PostgreSQL temporal.
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Construir la imagen de tu aplicación Docker.
      - name: Build Docker Image
        run: docker build -t pokemon-app .

      # 3. Ejecutar los tests de integración.
      - name: Run Integration Tests
        run: docker run --network host --env DATABASE_URL="postgresql://testuser:password@localhost:5432/test_db" pokemon-app npm run test:integration
